apiVersion: v1
kind: Service
metadata:
  name: cloudguard-kubernetes-service
spec:
  selector:
    app: accelerator
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
